version: '3.8'

services:
  hdfs:
    build:
      context: .
      dockerfile: docker/hdfs.Dockerfile
    ports:
      - "9870:9870" # WebHDFS port
      - "9000:9000" # NameNode port
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9870/webhdfs/v1/?op=LISTSTATUS"]
      interval: 10s
      timeout: 5s
      retries: 5

  presto:
    build:
      context: ./docker
      dockerfile: presto.Dockerfile
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/v1/info"]
      interval: 10s
      timeout: 5s
      retries: 5

  hive:
    build:
      context: .
      dockerfile: docker/hive.Dockerfile
    ports:
      - "10000:10000" # HiveServer2
      - "10002:10002" # Web UI
    healthcheck:
      # The hive service takes a while to start up.
      # This check waits for the HiveServer2 port to be open.
      test: ["CMD", "nc", "-z", "localhost", "10000"]
      interval: 10s
      timeout: 5s
      retries: 30
